# Generated by Django 5.2 on 2025-04-10 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('join_app', '0002_rename_user_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='phone',
            new_name='passwort',
        ),
    ]
