# Generated by Django 5.2 on 2025-04-10 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join_app', '0003_rename_phone_users_passwort'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestContacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('color', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('color', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('initial', models.TextField()),
                ('priotity', models.CharField(verbose_name=20)),
                ('priorityImg', models.TextField()),
                ('status', models.CharField(verbose_name=20)),
                ('title', models.CharField(verbose_name=255)),
                ('assignedTo', models.TextField()),
            ],
        ),
    ]
