# Generated by Django 5.2 on 2025-04-29 10:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join_app', '0004_guestcontacts_tasks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='priotity',
        ),
        migrations.AddField(
            model_name='tasks',
            name='category',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='tasks',
            name='priority',
            field=models.CharField(default='Medium', max_length=20),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='assignedTo',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='color',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='initial',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='priorityImg',
            field=models.TextField(default='./assets/img/vector_strich.svg'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='status',
            field=models.CharField(max_length=20),
        ),
    ]
