# Generated by Django 5.2 on 2025-04-29 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('join_app', '0005_remove_tasks_priotity_tasks_category_tasks_priority_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='priority',
        ),
    ]
