# Generated by Django 5.2 on 2025-04-29 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join_app', '0006_remove_tasks_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='priority',
            field=models.CharField(default='Medium', max_length=20),
        ),
    ]
