# Generated by Django 5.2 on 2025-04-29 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join_app', '0007_tasks_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
