# Generated by Django 5.2 on 2025-04-30 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join_app', '0010_alter_tasks_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='name',
        ),
        migrations.AlterField(
            model_name='tasks',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AddField(
            model_name='tasks',
            name='name',
            field=models.ManyToManyField(related_name='tasks', to='join_app.guestcontacts'),
        ),
    ]
