# Generated by Django 5.2 on 2025-04-30 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join_app', '0011_remove_tasks_name_alter_tasks_title_tasks_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='name',
        ),
        migrations.AlterField(
            model_name='tasks',
            name='title',
            field=models.CharField(verbose_name=255),
        ),
        migrations.AddField(
            model_name='tasks',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
