# Generated by Django 5.2 on 2025-04-30 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join_app', '0013_remove_tasks_name_tasks_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='name',
        ),
        migrations.AddField(
            model_name='tasks',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
