# Generated by Django 5.2 on 2025-04-30 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join_app', '0014_remove_tasks_name_tasks_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='name',
            field=models.TextField(default='[]'),
        ),
    ]
