# Generated by Django 5.2 on 2025-04-30 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join_app', '0016_alter_tasks_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='color',
            field=models.TextField(default=''),
        ),
    ]
