# Generated by Django 5.2 on 2025-04-30 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join_app', '0017_alter_tasks_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='selectedTask',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='tasks',
            name='subtasks',
            field=models.TextField(default=''),
        ),
    ]
